version: "3.8"
services:
  front-end:
    build:
      context: ./Techdome-frontend
    ports:
      - "3000:3000"
    networks: 
      - techdome-net
    depends_on: 
      - back-end

  back-end:
    build:
      context: ./Techdome-backend
    ports:
      - "5000:5000"
    networks:
      - techdome-net
    environment:
      DB_URI: mongodb://mongo:27017/techdome_db  # Update this line to set the MongoDB connection string
    depends_on:
      - mongo  # Update to depend on mongo service

  mongo:  # Change the database service to MongoDB
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - techdome-net

networks:
  techdome-net:
    driver: bridge

